#' Extract Components from an ExpressionSet List (i-Ome AI)
#'
#' This function extracts the expression matrix, phenotype data, and feature data 
#' from a named ExpressionSet object within a list generated by i-Ome AI.
#' 
#' - The `data` parameter controls sample inclusion:
#'     - `"clinical"`: only clinical samples
#'     - `"sample"`: full dataset, including technical replicates
#' - The `normalisation` parameter defines preprocessing:
#'     - `"loess_normalisation"` or `"median_normalisation"`
#' - If `ComBat = TRUE`, batch correction is applied by extracting the ComBat-adjusted matrix.
#' - The `ncf_select` option determines feature filtering based on the `ncf` column in featureData:
#'     - `"all"`: include all features
#'     - `"retain"`: include only features where `ncf == 'retain'`
#'     - `"filter"`: include only features where `ncf == 'filter'`
#'
#' @param ExpSet_list A named list of ExpressionSet objects.
#' @param data Character; either `"clinical"` or `"sample"`.
#' @param normalisation Character; either `"loess_normalisation"` or `"median_normalisation"`.
#' @param ComBat Logical; whether to extract batch-corrected data.
#' @param ncf_select Character; one of `"all"`, `"retain"`, or `"filter"` to filter features by `ncf`.
#'
#' @return A list containing:
#'   - \code{m}: The selected expression matrix from assayData.
#'   - \code{metadata}: Sample-level metadata (phenotype data).
#'   - \code{features}: Feature-level metadata.
#'   - \code{ExpSet}: The full ExpressionSet object (possibly filtered).
#'
#' @import dplyr
#' @import Biobase
#' @importFrom magrittr %>%
#' 
#' @export
#' @examples
#' result <- ExpSet_list_extract_function(my_ExpSet_list, "clinical", "loess_normalisation", TRUE, "retain")

ExpSet_list_extract_function <- function(ExpSet_list, 
																				 data = 'clinical', 
																				 normalisation = 'loess_normalisation', 
																				 ComBat = FALSE,
																				 ncf_select = 'retain') {
	
	# Build ExpressionSet name
	ExpSet_name <- paste0(data, '_ExpSet')
	ExpSet <- ExpSet_list[[ExpSet_name]]
	
	# Build matrix name
	matrix_name <- paste0(data, "_", normalisation)
	if (ComBat) {
		matrix_name <- paste0(matrix_name, '_ComBat')
	}
	
	# Filter features by `ncf`, if required
	if (!identical(ncf_select, 'all')) {
		ncf_features <- fData(ExpSet) %>%
			filter(ncf == ncf_select) %>%
			pull(Protein)
		ExpSet <- ExpSet[ncf_features, ]
	}
	
	return(list(
		m = ExpSet@assayData[[matrix_name]],
		metadata = pData(ExpSet),
		features = fData(ExpSet),
		ExpSet = ExpSet
	))
}
