#' Extract Components from an ExpressionSet List (i-Ome AI)
#'
#' This function extracts the expression matrix, phenotype data, and feature data 
#' from a named ExpressionSet object within a list generated by i-Ome AI.
#' 
#' - The `data` parameter controls sample inclusion:
#'     - `"clinical"`: only clinical samples
#'     - `"sample"`: full dataset, including technical replicates
#' - The `normalisation` parameter defines preprocessing:
#'     - `"loess_normalisation"` or `"median_normalisation"`
#' - If `ComBat = TRUE`, batch correction is applied by extracting the ComBat-adjusted matrix.
#' - The `ncf_select` option determines feature filtering based on the `ncf` column in featureData:
#'     - `"all"`: include all features
#'     - `"retain"`: include only features where `ncf == 'retain'`
#'     - `"filter"`: include only features where `ncf == 'filter'`
#'
#' @param ExpSet_list A named list of ExpressionSet objects.
#' @param data Character; either `"clinical"` or `"sample"`.
#' @param normalisation Character; either `"loess_normalisation"` or `"median_normalisation"`.
#' @param ComBat Logical; whether to extract batch-corrected data.
#' @param ncf_select Character; one of `"all"`, `"retain"`, or `"filter"` to filter features by `ncf`.
#'
#' @return A list containing:
#'   - \code{m}: The selected expression matrix from assayData.
#'   - \code{metadata}: Sample-level metadata (phenotype data).
#'   - \code{features}: Feature-level metadata.
#'   - \code{ExpSet}: The full ExpressionSet object (possibly filtered).
#'
#' @import dplyr
#' @import Biobase
#' @importFrom magrittr %>%
#' 
#' @export
#' @examples
#' result <- ExpSet_list_extract_function(my_ExpSet_list, "clinical", "loess_normalisation", TRUE, "retain")

ExpSet_list_extract_function <- function(ExpSet_list, 
																				 data = 'clinical', 
																				 normalisation = 'loess_normalised', 
																				 ComBat = FALSE,
																				 ncf_select = 'retain') {
	
	# Build ExpressionSet name
	ExpSet_name <- paste0(data, '_ExpSet')
	ExpSet <- ExpSet_list[[ExpSet_name]]
	
	# Build matrix name
	matrix_name <- paste0(data, "_", normalisation)
	if (ComBat) {
		matrix_name <- paste0(matrix_name, '_ComBat')
	}
	
	# Filter features by `ncf`, if required
	if (!identical(ncf_select, 'all')) {
		ncf_features <- fData(ExpSet) %>%
			filter(ncf == ncf_select) %>%
			pull(Protein)
		ExpSet <- ExpSet[ncf_features, ]
	}
	
	return(list(
		m = ExpSet@assayData[[matrix_name]],
		metadata = pData(ExpSet),
		features = fData(ExpSet),
		ExpSet = ExpSet
	))
}


#' Add Columns to phenoData (pData) of an ExpressionSet
#'
#' Merges new metadata columns into the `pData` slot of an `ExpressionSet` object.
#'
#' @param ExpSet An `ExpressionSet` object.
#' @param meta_add A data frame with `Sample` and columns to add.
#' @param add_cols Character vector of column names from `meta_add` to add to `pData`.
#'
#' @return The updated `ExpressionSet` object with modified `pData`.
#'
#' @note
#' Version 1.0 from  
#' ExpSet_functions.R
ExpSet_add_pData_function <- function(ExpSet, meta_add, add_cols) {
	print(phenoData(ExpSet)) 
	
	meta <- pData(ExpSet)
	
	cat(paste('\nAdd Metadata column(s):', paste(add_cols, collapse = ', '), '\n\n'))
	
	meta <- meta %>%
		dplyr::select(-any_of(add_cols)) %>%
		left_join(meta_add %>% dplyr::select(any_of(c("Sample", add_cols))), by = "Sample") %>%
		mutate(row_name = Sample) %>%
		column_to_rownames("row_name")
	
	pData(ExpSet) <- meta
	print(phenoData(ExpSet))
	
	return(ExpSet)
}


#' Add Columns to featureData (fData) of an ExpressionSet
#'
#' Merges new feature metadata columns into the `fData` slot of an `ExpressionSet` object.
#'
#' @param ExpSet An `ExpressionSet` object.
#' @param meta_add A data frame with `Protein` and columns to add.
#' @param add_cols Character vector of column names from `meta_add` to add to `fData`.
#'
#' @return The updated `ExpressionSet` object with modified `fData`.
#'
#' @note
#' Version 1.0 from  
#' ExpSet_functions.R
ExpSet_add_fData_function <- function(ExpSet, meta_add, add_cols, feature_column = 'Protein') {
	print(featureData(ExpSet))
	
	meta <- fData(ExpSet)
	
	cat(paste('\nAdd Metadata column(s):', paste(add_cols, collapse = ', '), '\n\n'))
	
	meta <- meta %>%
		dplyr::select(-any_of(add_cols)) %>%
		left_join(meta_add %>% dplyr::select(any_of(c(feature_column, add_cols))), by = feature_column) %>%
		mutate(row_name = !!sym(feature_column)) %>%
		column_to_rownames("row_name")
	
	fData(ExpSet) <- meta
	print(featureData(ExpSet))
	
	return(ExpSet)
}

